// <auto-generated />
using System;
using MemberComments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberComments.Migrations;

[DbContext(typeof(MemberCommentsDbContext))]
[Migration("20260428140000_AddCommentSubjectAndRichText")]
partial class AddCommentSubjectAndRichText
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

        modelBuilder.Entity("MemberComments.Data.Entities.Comment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AuthorName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<Guid>("ContentKey")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedUtc")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedUtc")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("EditedUtc")
                    .HasColumnType("TEXT");

                b.Property<Guid>("MemberKey")
                    .HasColumnType("TEXT");

                b.Property<int?>("ModeratorId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ParentId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(100000)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ContentKey");

                b.HasIndex("ParentId");

                b.ToTable("membercomments_Comment", (string)null);
            });

        modelBuilder.Entity("MemberComments.Data.Entities.Comment", b =>
            {
                b.HasOne("MemberComments.Data.Entities.Comment", "Parent")
                    .WithMany("Replies")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Parent");
            });

        modelBuilder.Entity("MemberComments.Data.Entities.Comment", b =>
            {
                b.Navigation("Replies");
            });
#pragma warning restore 612, 618
    }
}
